// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ0cw38ONqTiYHg5M_do8lajYFpYlJTlY',
    appId: '1:643638264859:web:f2087a758c3cd7136ee4be',
    messagingSenderId: '643638264859',
    projectId: 'operaciones-78-web',
    authDomain: 'operaciones-78-web.firebaseapp.com',
    storageBucket: 'operaciones-78-web.firebasestorage.app',
    measurementId: 'G-40CRWWRM0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAE-QVnR1G6N59SI0l6QoF2gjqgD-Mzoo',
    appId: '1:643638264859:android:ce44513d3c4341246ee4be',
    messagingSenderId: '643638264859',
    projectId: 'operaciones-78-web',
    storageBucket: 'operaciones-78-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxZGPK9v9LLBZbrAdyese5F-GKCho4RNU',
    appId: '1:643638264859:ios:3fbb1f0a39d5bdbd6ee4be',
    messagingSenderId: '643638264859',
    projectId: 'operaciones-78-web',
    storageBucket: 'operaciones-78-web.firebasestorage.app',
    iosBundleId: 'com.example.operaciones78Web',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxZGPK9v9LLBZbrAdyese5F-GKCho4RNU',
    appId: '1:643638264859:ios:3fbb1f0a39d5bdbd6ee4be',
    messagingSenderId: '643638264859',
    projectId: 'operaciones-78-web',
    storageBucket: 'operaciones-78-web.firebasestorage.app',
    iosBundleId: 'com.example.operaciones78Web',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ0cw38ONqTiYHg5M_do8lajYFpYlJTlY',
    appId: '1:643638264859:web:8c119ffc3293b3f46ee4be',
    messagingSenderId: '643638264859',
    projectId: 'operaciones-78-web',
    authDomain: 'operaciones-78-web.firebaseapp.com',
    storageBucket: 'operaciones-78-web.firebasestorage.app',
    measurementId: 'G-120L4JZWRQ',
  );
}
